language: ruby
rvm:
- 2.1.1
deploy:
  provider: heroku
  api_key:
    secure: iImCosdiPuZ+0dLR/Yg9+y0AOBaAjs3otKlQqFueEcL1cxISPz5ldw/Kqdf4/+0GuV5s4N2UDT90F4dUqBHhCmvOpuo2iktbAbGAcu6HM3G/EoqEkCN9De/BXlgAYO+sxdY/sfOQReTIOjc07ctcMvcn7xTc8eVEy9cRxWAJtoU=
  app: clinical-trial-match
  on:
    repo: mwenger1/clinical_trial_match
