language: ruby
rvm:
- 2.1.1
deploy:
  provider: heroku
  api_key:
    secure: UJsiZbd0MdoLFS6hA38Z3KW78qNJew0CyWoigbv7sv5uE/eMMPJZMDffEkfQ90jQU+iL3S5XUPbHpZmJph/qBUl1CqMLrPI99B6+7/vOzs30ZfQdTEx+UVyl011/3w9MKazphrKr7OpjwIVHwWA7uNxDbPZWEgR3mZlXEQs0qJE=
  app:
  	master: clinical-trial-match
    development: dev-clinical-trial-match
    celiac-foundation: celiac-foundation
    staging: st-clinical-trial-match

  on:
    repo: mwenger1/clinical_trial_match
