language: ruby
rvm:
- 2.1.1
deploy:
  provider: heroku
  api_key:
    secure: BatuYro7a4cOv7gZdMgpxGXpM5Nl+3WZ4K0eLost2Qkjms3vqQAhUvQ5R/YXY51MtQjQF0ghPyQjvfBAqw/cpi36iOdaqibdy1dBHKcfjXakApygao3vFk7vJnoabcRzhxthck1XBjieAOWd4BZRNUY6BQVCGhzuHVVcSuUCPt8=
  app:
    master: clinical-trial-match
    staging: st-clinical-trial-match
    development: dev-clinical-trial-match
  on:
    repo: mwenger1/clinical_trial_match
before_install:
  - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev qtlocation5-dev qtsensors5-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev qt4-default
notifications:
  email: false
  slack:
    secure: QeiDe7/uJ4OIVIYQf4iOhCym3IW3nZxw+czl0zoWlWW7aHWSFb6uVKW0omgM5k7M24a13zbKk9OvgHgw/q/SstbxovmC/w9vTU+JqP6912XzP0yg4yQJWooz/DtNraUHDBMAOBxqeH3kNJMlw1qJmZTRz2li1v3IwSquf2Lrt8E=
